function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BallAndBeamODEMatrices
%    [W,RHS] = BallAndBeamODEMatrices(IN1,To,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    21-Feb-2023 13:49:38

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
g = in3(4,:);
theta = in1(2,:);
x = in1(1,:);
t2 = sin(theta);
t3 = M.*R.*(3.0./5.0);
t4 = -t3;
W = reshape([M.*(7.0./5.0),t4,t4,J+M.*R.^2.*(7.0./5.0)+M.*x.^2],[2,2]);
if nargout > 1
    RHS = [-M.*(g.*t2+dtheta.^2.*x);To+M.*g.*(R.*t2-x.*cos(theta))];
end
